# Generated by Django 4.0 on 2022-08-26 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FWP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='day',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_even',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FWP.parity'),
        ),
    ]
